language: go
go:
  - 1.12.x
  - 1.11.x
  - 1.10.x
os:
  - linux
  - osx
sudo: required
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
  - go get -d ./...
script:
  - go build -tags=gofuzz ./...
  - go vet ./...
  - staticcheck ./...
  - golint -set_exit_status ./...
  - go test -v -race ./...
  - go test -c -race -tags=integration .
  - sudo ./netlink.test -test.v -test.run TestLinuxConnIntegration*
